config/routes.rb
Rails.application.routes.draw do
  get 'movies/new'
  get 'movies/create'
  get 'lists/index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root to: 'lists#index'

  resources :lists do
    resources :bookmarks
  end

  resources :bookmarks, only: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list

  validates :movie, presence: true
  validates :comment, length: { minimum: 6 }
  validates :list, presence: true
  validates_uniqueness_of :movie_id, scope: :list_id
end

app/models/list.rb
class List < ApplicationRecord
  has_many :bookmarks
  has_many :movies, through: :bookmarks, dependent: :destroy
  has_one_attached :photo

  validates :name, presence: true
  validates :name, uniqueness: true
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks

  validates :title, uniqueness: true
  validates :title, presence: true
  validates :overview, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  def new
    @list = List.find(params[:list_id])
    @bookmark = Bookmark.new
  end

  def create
    @list = List.find(params[:list_id])
    @bookmark = Bookmark.new(bookmark_params)
    @bookmark.list = @list

    if @bookmark.save
      redirect_to list_path(@list), notice: "bookmark was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @bookmark = Bookmark.find(params[:id])
    @bookmark.destroy
  end

  private

  def bookmark_params
    params.require(:bookmark).permit(:comment, :movie_id)
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def index
    @lists = List.all
  end

  def show
    @bookmark = Bookmark.find(params[:id])
    @movie = Movie.find(params[:id])
    # @bookmark = Bookmark.all
    @list = List.find(params[:id])
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)

    if @list.save
      redirect_to @list, notice: "list was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def list_params
    params.require(:list).permit(:name, :photo)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/views/bookmarks/new.html.erb
<h1>Bookmark Movie</h1>

<%= @bookmark.comment %>

<%= simple_form_for [@list, @bookmark] do |f| %>
  <%= f.input :comment %>
  <%= f.association :movie %>
  <%= f.submit "Add comment", class: "btn btn-primary" %>
<% end %>

app/views/layouts/_navbar.html.erb
<div class="navbar">
  <div class="logo">
    <%= image_tag "logo.png", alt: "Le Wagon Logo", width: 30 %>
  </div>
  <p><%= link_to 'New List', new_list_path %></p>
</div>
<div class="hero">
  <p>Save any kind of movies <br> Classic</p>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/lists/index.html.erb
<%= render "layouts/navbar" %>
<div class="container">
  <div class="my-list">
  <h3>My List</h3>
  <p class="btn"><%= link_to 'Create a movie list' %></p>
  <%= cl_image_tag @list.photo.key, height: 300, width: 400, crop: :fill %>
  </div>
  <ul>
    <% @lists.each do |list| %>
      <li><%= link_to list.name, list_path(list) %></li>
    <% end %>
  </ul>
</div>

app/views/lists/new.html.erb
<h1>New List</h1>

<%= simple_form_for (@list) do |f| %>
  <%= f.input :name %>
  <%= f.submit "Create List", class: "btn btn-primary" %>
<% end %>

app/views/lists/show.html.erb
<div class="navbar">
  <div class="logo">
    <%= image_tag "logo.png", alt: "Le Wagon Logo", width: 30 %>
  </div>
  <p><%= link_to 'Bookmark a Film', new_list_bookmark_path(@list) %></p>
</div>
<div class="hero">
  <p><%= @list.name %></p>
</div>

<div class="cardx">
  <div class="img-bg"></div>
  <div class="card-context">
      <p><%= @movie.title %> <span><%= @movie.rating %></span> </p>
      <p><%= @movie.overview %></p>
    <div class="bottom">
      <p><%= @bookmark.comment %></p>
      <p><%= link_to 'Delete' %></p>
    </div>
  </div>
</div>